
# 変数名に関する制約
#identifier_name:
#  allowed_symbols: "_"
#  min_length: 1
#  excluded:
#    - i
#    - j
#    - n
#    - x
#    - y
line_length: 200
function_body_length: 200
disabled_rules:
- type_body_length
- function_parameter_count
- file_length

# force_castは場合によっては使用するため
- force_cast
- force_try
- cyclomatic_complexity
- trailing_whitespace
- identifier_name
- type_name

excluded:
- Pods/
- Carthage/


